language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t geckobjj/docker-react-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true geckobjj/docker-react-workflow npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-workflow"
  env: "Dockerreactworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-148228404143"
  bucket_path: "docker-react-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY